### ISSUE TITLE
JSONPath Query results always have [ ] around them

### ISSUE THREAD

**Issue by syats** [carml/carml#22]
Hi,

Templates that have JSONPath queries are not being properly returned. Some square bracket characters and quotes are being appended to the result. Maybe there is a missing step in the parsing of the JSONPath result?

## The RML:

> 
> 
> @prefix rr: <http://www.w3.org/ns/r2rml#>.
> @prefix rml: <http://semweb.mmlab.be/ns/rml#>.
> @prefix ex: <http://example.com/>.
> @prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
> @prefix ql: <http://semweb.mmlab.be/ns/ql#> .
> 
> <#SubjectMapping> a rr:TriplesMap;
> 	rml:logicalSource [
> 		rml:source "simpleTestInput.json";
> 		rml:referenceFormulation ql:JSONPath;
> 		rml:iterator "$"
> 	];
> 
> 	rr:subjectMap [
> 		rr:template "http://example.com/Child/{first}/{last}";
> 		rr:class ex:Child
> 	];
> 	
> 	rr:predicateObjectMap [
> 		rr:predicate ex:BSN;
> 		rr:objectMap [
> 			rr:template "ex:{$..[?(@['ver']==1) ]['val']}";
> 		];
> 	].
> 

## The Json being mapped:

> 
> [{
> 	"first"	: "Amarise",
> 	"last"	: "Fernand",
> 	"loves"	: "milk",
> 	"birthday" : "2017-02-16",
> 	"language"	: "Nederlands",
> 	"age"	: "5",
> 	"length"	: "5.5",
> 	"BSN"	: {    "ver":1,
> 			"val":"AaX"
> 			},
> 	"BSN2"	: {    "ver":2,
> 		       "val":"BbX"
> 			},
>               
> 	"parents": "Gea and Hildebrand",
> }]

## The result:

> (http://example.com/Child/Amarise/Fernand, http://www.w3.org/1999/02/22-rdf-syntax-ns#type, http://example.com/Child) [null]
> (http://example.com/Child/Amarise/Fernand, http://example.com/BSN, ex:%5b%22AaX%22%5d) [null]
> 

Notice the encoded characters around AaX

Thanks for any feedback!

**Comment by pmaria** [comment]
Hi @syats,

The problem here is that the result of a JsonPath filter is always a list.
If you were to use `"$.BSN.val"` the result would be as you expected.

There doesn't seem to be a way to get a value out of a filtered list.
See also: https://github.com/json-path/JsonPath/issues/272

I guess this could be useful when you know for certain that a list can be filtered down to a singular item.
If you would really need to select items based on a filter like this you would have to move the filter in to a specific iterator and create a triples map specifically for creating triples based on that iterator.

Hope this helps.

Pano

**Comment by syats** [comment]
Thanks @pmaria !

The RML spec isn't really clear about how to handle this case. 

My suggestion would be that if the result of a JSONPath expression is a list, then the mapping gets applied to each element of the list. This is consistent with the evaluation of template "http://loc.example.com/city/{$.venue[*].location.city}" done in section [9.2 of the spec](http://rml.io/spec.html#example-input). 

Do you think this could be implemented into carml? 
(If you give me a pointer I can try implementing it myself and make a PR)

Victor

**Comment by pmaria** [comment]
Hi @syats,

Interesting idea. Do you have a lot of datasets where you would need such functionality?

Currently, as RML is basically a direct abstraction of R2RML, and this isn't part of R2RML, it isn't in RML either.
So this would have to be a new construct. Something like a `MultiTermMap` that requires `multiTemplate` and `multiReference` perhaps. But this would have to be investigated further.
As we're currently not involved in the RML spec development I hesitate. We could add and develop such a construct as an extension in CARML, although since this is quite a fundamental extension, preferrably, this would be something to discuss with the RML spec developers.

**Comment by syats** [comment]
Hi @pmaria ,

Yes, we have many files like that.
In any of the links in this site
http://adequate-project-pp.semantic-web.at/GraphSearch/
you can click on an item and then on the metadata link (e.g.  http://adequate-project.semantic-web.at:5003/www_opendataportal_at/anzahl-der-unternehmensneugrundungen-ab-1993/blob/master/metadata.jsonld  )
In the above example, I would like to get, for example, the dcat indentifier. The JSONPath would be:

$.[?(@.['@type'][0] == 'http://www.w3.org/ns/dcat#Dataset')]['http://purl.org/dc/terms/identifier'][0]['@value'] 

I would be thankful for any other suggestions you might have,
Victor

**Comment by pmaria** [comment]
@syats interesting. So you want to use RML on expanded JSON-LD RDF documents, presumably then to create completely new RDF? I would be interested to know more about the application, that is if you're allowed to share that.

One option to work around this issue is to compact or flatten the JSON-LD first, see e.g. http://tinyurl.com/yc9xlnv7 , which might solve your problem. Also creating a custom frame could help.

However that's not a solution for non JSON-LD sources.

**Comment by syats** [comment]
Hi!
Ineed, the idea was to be able to map any json file, in particular JSON-LD.  
The idea is to implement a service where one can upload metadata in arbitrary format, build (using a UI) a RML to map it into a standar format, and save the metadata in that standard format. In the case where the upload is JSON-LD, indeed one could do other approaches, but it would be nice to have as few "special cases" as possible.  

My solution to this issue was to wrap CARML in such a way that the objects of the resulting statements are analyzed for the pattern [a,b,c,d] and if such is found, converted into multiple statements. Not elegant, but works.  Further clearning up operations were required, so wrapping was necessary in any case.

Thanks for your input, I will continue to bother you soon with other issues.
