### ISSUE TITLE
Why multiReference?

### ISSUE THREAD

**Issue by VladimirAlexiev** [carml/carml#52]
I have perhaps a naive question.
Looking at the example in the readme, "cars" returns an array. So this array should emit multiple rdf object values, what else could it emit?
Seems to me you need to extend/fix the rml implementation, but not necessarily the rml language?

**Comment by pmaria** [comment]
Hi @VladimirAlexiev ,

Thanks for looking at this critically!

The reason we chose to introduce these multi* terms to realise multiplicity in term generation is because, in our opinion, the RML vocabulary doesn't define any such behavior. For example, according to R2RML a termmap is "A function that generates an RDF term from a logical table row.". RML doesn't seem to define an rml:TermMap stating that it can generate one or more RDF terms. Therefor, it is unclear what is expected to happen when an expression returns a representation of multiple values.

However, I agree that in many cases it would be logical to generate multiple terms by default.
I believe it would be good to discuss this and other topics in a larger setting, to see if we can clarify the current RML spec. Perhaps that will lead us to the same conclusion.

**Comment by VladimirAlexiev** [comment]
Right! You don't need  a new class `rml:TermMap`: the RML spec could clarify what happens with the standard class `rr:TermMap` when a data access returns multiple values.
Please note that http://rml.io/RMLmappingLanguage.html says "An Object Map specifies how the triple's object(s) are generated" (note the plural); and generates two instances from this data:
```json
"People": [ { "name": "Anastasia",  "surname": "Dimou" },
                      { "name": "Ruben", "surname": "Verborgh" } ],
```
The iterator does not explicitly iterate over People (though it uses a wrong field name)
```ttl
rml:iterator "$.[*].Person"
```
So the two values must be due to the "natural" iterative behavior discussed here

**Comment by ktk** [comment]
Just FYI I'm very grateful for the functionality, very useful in XML files. Also I do see cases where it would be nice to have on the subject itself but there are ways around it I think.

**Comment by VladimirAlexiev** [comment]
> cases where it would be nice to have on the subject itself

@ktk, can you clarify what you mean here?

**Comment by VladimirAlexiev** [comment]
@pmaria: I think https://github.com/RMLio/rml-implementation-report/issues/11 clarifies the `carml:multiReference` extension is not needed: that's the expected behavior for multivalued fields.
Cheers!

**Comment by pmaria** [comment]
Thanks @VladimirAlexiev . Will look at this soon.

**Comment by pmaria** [comment]
The multi term map extension is deprecated with release v0.3.0.
