### ISSUE TITLE
MultiTermMap extension for CSV

### ISSUE THREAD

**Issue by fekaputra** [carml/carml#53]
Hi, I wonder whether there is a plan to work on the multitermmap for CSV. In my case, there are multiple (well.. up to hundreds) values/entries separated by ';' in a single CSV cell.

ps: thanks to carml team for the nice engine!

**Comment by pmaria** [comment]
Hi @fekaputra ,

No, currently no plans for this. 
The problem is that there is no standard for multidimensional CSV (, at least, that I know of).

What you could do in this case is use the function extension. You could create a function that parses the csv value representing multiple entities and returns a `List<>` of values. Then specify the execution of that function in the mapping using `carml:multiFunctionValue` instead of `fnml:functionValue`.

Let me know if that helps.

Cheers,
Pano

**Comment by fekaputra** [comment]
Thanks for the reply! I'll check it out.
