### ISSUE TITLE
Predicates of type IRI don't seem to get values from JSON

### ISSUE THREAD

**Issue by syats** [carml/carml#54]
Hi again!
I have an rml file that is supossed to create some triples whose predicates are IRIs. I want' these IRIs to come from a URL in the json. 
While the input file contains the following key value pair:
`"license_url": "https://creativecommons.org/licenses/by/3.0/at/deed.de", `
The out put contains the following triple
`http://my.resources/my.resource ; 	 http://purl.org/dc/terms/license ; 	 http://none.com/https%3a%2f%2fcreativecommons.org%2flicenses%2fby%2f3.0%2fat%2fdeed.de`
which means the URL is being interpreted as a string.
I don't think this is intenteded behaviour, but maybe I am doing something wrong.
The mapping for this is

> rr:predicateObjectMap
>     [
>       rr:predicate dc:license;
>       rr:objectMap
>       [
>           rr:template "{$.[\"license_url\"]}";
>           rr:termType rr:IRI;
>       ];
>     ].
> 

Find attached the mapping and the input file, renamed to txt to allow for attaching :p 
Any help is appreciated,

Victor

[testing.rml.txt](https://github.com/carml/carml/files/2145041/testing.rml.txt)
[testing.input.json.txt](https://github.com/carml/carml/files/2145042/testing.input.json.txt)

**Comment by pmaria** [comment]
Hi @syats,

The `rr:template` will create an IRI-safe version of the reference enclosed in curly braces, as per the [R2RML spec](https://www.w3.org/TR/r2rml/#from-template). This means that it will encode the value as `https%3a%2f%2fcreativecommons.org%2flicenses%2fby%2f3.0%2fat%2fdeed.de`. Then because the base IRI in CARML is set to `http://none.com/` by default, this is prepended.

The solution here would be to use `rml:reference` instead of `rr:template` to get the IRI value without encoding it.

Kind regards,
Pano

**Comment by syats** [comment]
Thanks @pmaria ,
That made the trick.  Just in case someone stumbles into this in the future, I would like to note that the syntax for jsonpath/xpath expression is different between rr:template and rml:reference:  in the case of rml:reference no curly brackets should surround the expression.

Best,
Victor
