### ISSUE TITLE
why  Missing property in path ?

### ISSUE THREAD

**Issue by miyamotodan** [carml/carml#55]
why you cannot ignore the mapping (ex: predicateObjectMap) and go on with others?
have I to provide always the same JSON structure with all the properties I mapped?

thanks in advance

**Comment by miyamotodan** [comment]
sorry, i'm too cryptic :-)

I have 2 json file, "schedaRA" works fine with my mapping, "schedaRA_mod" is the same file but I've deleted a nested piece of information "OGTT" because sometimes I don't have it in my data.
With the "mod" file I got "Missing property in path $['OG']['OGT']['OGTT']".

I hoped it could be ignored by the processor...

Maybe I'm wrong using jsonpath in tis way? 

[example.zip](https://github.com/carml/carml/files/2165757/example.zip)

**Comment by pmaria** [comment]
Hi @miyamotodan,

It seems this is expected behavior for Jayway's JSONPath implementation. The solution is to add `Option.SUPPRESS_EXCEPTIONS` to the JSONPath configuration. I will add this to the next release.

In the meantime you could copy the JsonPathResolver code and use your own with this extra configuration.

I hope to get the fix out soon.

**Comment by miyamotodan** [comment]
Thaks a lot!
