### ISSUE TITLE
URI of FnO and Functions Subjects

### ISSUE THREAD

**Issue by dachafra** [carml/carml#83]
The URI of the FnO has changed from "http://semweb.datasciencelab.be/ns/function#" to "http://w3id.org/function/ontology#". The engine is not able to parse mapping with functions with the current URI.

Why does the function value (fnml:functionValue) need an explicit subject? It is not mandatory as it can be seen in the examples: https://fno.io/rml/ (only LogicalSource and PredicateObjectMap).

**Comment by pmaria** [comment]
Hi @dachafra thanks for the heads up on the change of the URI. I will update this soon.

As for your other question. The reason is that we interpreted a FunctionMap to be a sub-class of TriplesMap. And the [rules for a valid TriplesMap](http://rml.io/spec.html#triples-map) state that it requires exactly one SubjectMap. The behaviour of not providing a Subject Map is not defined anywhere that I know of.

**Comment by pmaria** [comment]
The old URI is deprecated in favor of the new URI with release v0.3.0
